### ISSUE TITLE
Scope no such file or directory

### ISSUE THREAD

**Issue by mulibu-flyingk** [criblio/cribl-demo#36]
Hi all,

after updating to the latest version on master branch (version tag v1.7-118-gec1ea57) I am getting the following error when executing the start.sh script:

`./start.sh: line 9: ./scope: No such file or directory`
`error: no objects passed to apply`

Am I missing something or is that a bug?

Kind regards
Chris

**Comment by stevelitras** [comment]
Thanks Chris - It was a bug - I've wrapped that line to check for the scope executable before attempting that.
